### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by da4throux** [overflOw11/MMM-Netatmo-Thermostat#2]
hi,
thanks for the module, I get this error in the console when the browser is loadimg (MMM is up to date, all my other modules working fine)
not sure how to troubleshoot this....

Uncaught TypeError: Cannot read property 'body' of undefined
    at Class.renderAll (:8080/modules/MMM-Netatmo-Thermostat//MMM-Netatmo-Thermostat.js:61)
    at e (:8080/modules/MMM-Netatmo-Thermostat/q.min.js:1)
    at h.promiseDispatch.j (:8080/modules/MMM-Netatmo-Thermostat/q.min.js:1)
    at o.d.promiseDispatch (:8080/modules/MMM-Netatmo-Thermostat/q.min.js:1)
    at :8080/modules/MMM-Netatmo-Thermostat/q.min.js:1
    at b (:8080/modules/MMM-Netatmo-Thermostat/q.min.js:1)
    at a (:8080/modules/MMM-Netatmo-Thermostat/q.min.js:1)

any pointers ?
thanks

**Comment by overfl0w11** [comment]
Hi,

Can you check in the network tab of your developper console if the request to the netatmo api have a 200 OK response or anything else.

Thx

**Comment by da4throux** [comment]
The error happens before the request can occur.
The module requires jquery to operate so I had to add it manually (like you did for q), I can do a pull request for that if you want.
I assume some users already use some module with jquery, and do not get this issue maybe.

**Comment by overfl0w11** [comment]
I'm not sure you have to add JQuery manually. 
The function renderAll is called after request is sent to netatmo api so when the TypeError occurs, the request is already sent. This error is trigger because of the following line :

`this.processData(data.body.devices[0]);`

The error explains that the `data` object is undefined, and that it can't read property `body` of the undefined object `data`.


In addition, I think the MagicMirror modules are hermetic. So even if you have a dependency that is imported into a module, you will have to redo your import to use it in a different module.

**Comment by da4throux** [comment]
I'm not sure about my analysis, but:
 - the code is using Jquery for an Ajax call, and until I added it manually it always add an error there ($, and the error I mentioned), and now I have the little circle there
 - the jQuery had to come from somewhere, I assumed another module (in the webpage, I would imagine imported libraries are reachable, but that might be wrong), else I'd like to know 😄 
I'll pull the new branch and see if I have still have the error.

**Comment by da4throux** [comment]
Just to confirm: after pulling the new version I had the error again, and manually adding jQuery solved the issue

**Comment by overfl0w11** [comment]
Ok.

Thx for the feedback. You are right, I have to add JQuery manually.
I just don't understant from where Jquery is imported in my MagicMirror. I will check this tonight. 

If you want, you can do a pull request. Else, I will correct this tonight.

**Comment by da4throux** [comment]
Hi
thanks all lot for the module, I just did a PR.
